name: note_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  auto_route: ^5.0.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_feather_icons: ^2.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.1.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
